(function(){function f(){this.a=window._sf_async_config||{};this.u=i(this,this.w);this.m=0;j(this)}function i(a,b){return function(){b.apply(a,arguments)}}function l(){var a,b,c;a="";for(c=0;c<16;c++){b=Math.floor(Math.random()*36).toString(36);a+=b}return a}function m(a,b,c){a.a[b]=a.a[b]||c}
function j(a){if(!n("_SUPERFLY_nosample")){a.f=0;a.j=0;a.r=o();a.l=true;a.h=null;for(var b=document.getElementsByTagName("script"),c=0;c<b.length;c++)if(b[c].src.match(/(chartbeat|chartbeatdev|chartbeat_raw).js/)){var d=b[c];break}if(d){c=d.src.split("?")[1];b={};if(c){if(c.charAt(0)=="?")c=c.substring(1);c=c.replace("+"," ");c=c.split(/[&;]/g);for(d=0;d<c.length;d++){var e=c[d].split("=");b[decodeURIComponent(e[0])]=decodeURIComponent(e[1])}}m(a,"uid",b.uid);m(a,"domain",b.domain)}b=window.location;
m(a,"pingServer","ping.chartbeat.net");m(a,"title",document.title);m(a,"domain",b.host);e=window.location;c=e.pathname+(e.search||"");c=c.replace(/PHPSESSID=[^&]+/,"");d=/&utm_[^=]+=[^&]+/ig;if(e=d.exec(e.search))c=c.replace(d,"");d=/\?utm_[^=]+=[^&]+(.*)/i;if(e=d.exec(c))c=c.replace(d,e[1]!=""?"?"+e[1]:"");m(a,"path",c);a.z=l(a);a.n=b.host;a.n=a.n.replace(/^www\./,"");a.a.domain=a.a.domain.replace(/^www\./,"");a.d=n("_chartbeat2");a.p=0;if(!a.d){a.d=n("_chartbeat");if(a.d)n("_chartbeat")&&p("_chartbeat",
"",-1);else{a.p=1;a.d=l(a)}}p("_chartbeat2",a.d,30);if(a.v)a.k();else{a.v=true;a.g=new q;if(window._sf_async_config)a.k();else{a=i(a,a.k);if(typeof window.addEventListener!="undefined")window.addEventListener("load",a,false);else if(typeof document.addEventListener!="undefined")document.addEventListener("load",a,false);else typeof window.attachEvent!="undefined"&&window.attachEvent("onload",a)}}}}
f.prototype.A=function(a,b){this.s=window.location.protocol+"//"+this.a.domain+this.a.path;this.a.path=a;if(b)this.a.title=b;window.clearInterval(this.i);j(this)};f.prototype.t=function(a){this.h=a};f.prototype.k=function(){var a=window._sf_startpt,b=window._sf_endpt;if(typeof a=="number")this.q=typeof b=="number"?b-a:o()-a;this.i=window.setInterval(i(this,this.o),15E3);this.o()};
f.prototype.w=function(){this.m++;if(this.m<3){this.l=true;r(this)}else{clearInterval(this.i);p("_SUPERFLY_nosample","1",0.0070)}};function r(a){var b=a.f;b=b?Math.min(b*2,16):1;a.f=b}
f.prototype.o=function(){var a;a:{a=this.g;for(var b=0;b<a.e.length;b++)if(a.b[a.c][a.e[b]]){a=true;break a}a=false}s(this.g);if(this.j<this.f&&!a)this.j++;else{if(a)this.f=0;else r(this);this.j=0;a=t(this);var c=b=0,d=0;if(u(this.g,"onkeydown"))c=1;else if(u(this.g,"onmousemove")||u(this.g,"onscroll"))b=1;else d=1;var e=this.a,g="",h="",k=window.location;if(this.l){this.l=false;if(this.s){g=this.s;h=true}else{g=document.referrer||"";h=g.indexOf("://"+k.host+"/")!=-1}g=(h?"&v=":"&r=")+encodeURIComponent(g);
h=e.title.slice(0,100);h="&i="+encodeURIComponent(h)}var w=this.q?"&b="+this.q:"",x=this.h?"&A="+this.h:"",y=e.sections?"&g0="+encodeURIComponent(e.sections):"",z=e.authors?"&g1="+encodeURIComponent(e.authors):"",A=(k.protocol||"http:")+"//"+e.pingServer+"/ping?h="+encodeURIComponent(e.domain)+"&p="+encodeURIComponent(e.path)+"&u="+this.d+"&d=";k=k.host.replace(/^www\./,"");a=A+encodeURIComponent(k)+"&g="+e.uid+y+z+"&n="+this.p+"&c="+Math.round((o()-this.r)/600)/100+"&x="+a+"&y="+(document.body.scrollHeight||
0)+"&w="+(window.innerHeight||document.body.offsetHeight||0)+"&j="+Math.round((this.f+2)*15E3/1E3)+"&R="+b+"&W="+c+"&I="+d+g+w+x+"&t="+this.z+h+"&_";b=new Image(1,1);b.onerror=this.u;b.src=a;o()-this.r>72E5&&window.clearInterval(this.i)}};function t(){var a=window,b=document.body,c=document.documentElement;if(typeof a.pageYOffset=="number")return a.pageYOffset;else if(b&&b.scrollTop)return b.scrollTop;else if(c&&c.scrollTop)return c.scrollTop;return 0}
function q(){this.e=[];this.b=[{},{},{},{}];this.c=0;v(this,window,"onscroll");v(this,document.body,"onkeydown");v(this,document.body,"onmousemove");s(this)}function v(a,b,c){var d=b[c]||function(){};a.e.push(c);b[c]=function(e){d.apply(this,arguments);if(e&&c=="onkeydown"){var g=e.keyCode?e.keyCode:e.which;if(g==32||g>36&&g<41){a.b[a.c].onscroll++;return}}a.b[a.c][c]++}}function u(a,b){for(var c=0,d=0;d<a.b.length;d++)c+=a.b[d][b]||0;return c}
function s(a){a.c=(a.c+1)%a.b.length;for(var b=0;b<a.e.length;b++)a.b[a.c][a.e[b]]=0}function n(a){a=a+"=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(a)==0)return d.substring(a.length,d.length)}return null}function p(a,b,c){var d=new Date;d.setTime(o()+c*864E5);document.cookie=a+"="+b+("; expires="+d.toGMTString())+"; path=/"}function o(){return(new Date).getTime()}window.pSUPERFLY=new f;
f.prototype.virtualPage=f.prototype.A;f.prototype.activity=f.prototype.t;})();
