# See http://github.com/eugenebolshakov/app_config
# parsed as ERB & YAML
# accessible as Conf.whatever
# NB must reload app after changing this file

common:
  # Change the secret to protect your site from DoS attack
  # secret: 8_2BGh0
  # The array of feeds you want to aggregate. If you change this then manually delete the whole cache.
  feeds:
   - http://www.quidnuncre.com/posts.atom
   - http://ny.curbed.com/atom.xml
   - http://www.costar.com/News/RSS/RSS.aspx?m=NYC
   - http://www.dnainfo.com/new-york/index/all
   - http://feeds.crainsnewyork.com/crainsnewyork/deals
   - http://feeds.feedburner.com/inmannews?format=xml
   - http://rss.nytimes.com/services/xml/rss/nyt/RealEstate.xml
   - http://rss.nytimes.com/services/xml/rss/nyt/Commercial.xml
   - http://feeds.feedburner.com/trdnews?format=xml
   - http://www.ny1.com/Rss/Feeds.aspx?SecID=1000
   # - http://nypost.com/real-estate/feed/
   # - http://nymag.com/rss/Real_Estate.xml
   # - http://www.mortgagenewsdaily.com/channels/mortgage_rates_update/rss.aspx
   # - http://feeds.wsjonline.com/wsj/video/real-estate/feed?format=xml
   # - https://www.rcanalytics.com/public-articles.xml
  # A map between the original feed item titles in the XML, and the titles you want to show when rendered.
  # In other words, you can change how the individual feed items are labelled.

# Original Feeds List
  # The Real Deal
  # Curbed
  # DNA Info
  # GlobeSt.com
  # Crain’s New York Business
  # Inman News
  # NY1 Real Estate
  # NYT Real Estate
  # Wall Street Journal Real Estate
  # CoStar

  #Added
  # New York Post
  # New York Mag
  # Mortgage News Daily
  # Wall Street Journal Video News Real Estate
  # Real Capital Analytics Commercial Real Estate News

#development:

#test:

#deployment:
