development:
    adapter: mysql
    database: qre_development
    username: root
    password:
    host: localhost

test:
    adapter: mysql
    database: qre_test
    username: root
    password:
    host: localhost
    pool: 5

production:
    adapter: mysql
    database: qre_production
    pool: 5
    timeout: 5000
    username: qre_production
    password: qre_production
    host: flipstone.ctf5dd2ocka6.us-east-1.rds.amazonaws.com
