# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: Quidnunc Beta
url:   http://quidnuncre.com
exception_notifications: patrick.kennedy@quidnuncre.com
author:
  name:    Quidnunc Team        # For copyright notice and ATOM feeds

# https://profiles.google.com/u/0/103382573522916598862